import type { TripPlan } from "../../types/trip";

type Props = {
  overview: TripPlan["overview"];
};

const TripOverview = ({ overview }: Props) => {
  return (
    <div className="overflow-hidden rounded-3xl bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 p-8 text-white shadow-2xl">

      <div className="flex items-center justify-between">
        <div>
          <p className="text-sm uppercase tracking-widest opacity-80">
            AI Travel Planner
          </p>

          <h2 className="mt-2 text-4xl font-bold">
            🌍 {overview.destination}
          </h2>

          <p className="mt-2 text-blue-100">
            Your personalized AI-generated itinerary
          </p>
        </div>

        <div className="hidden md:block text-7xl">
          ✈️
        </div>
      </div>

      <div className="mt-10 grid gap-6 md:grid-cols-4">

        <div className="rounded-2xl bg-white/15 p-5 backdrop-blur">
          <p className="text-sm opacity-80">📅 Duration</p>
          <p className="mt-2 text-2xl font-bold">
            {overview.duration}
          </p>
        </div>

        <div className="rounded-2xl bg-white/15 p-5 backdrop-blur">
          <p className="text-sm opacity-80">💰 Budget</p>
          <p className="mt-2 text-2xl font-bold">
            ₹ {overview.budget}
          </p>
        </div>

        <div className="rounded-2xl bg-white/15 p-5 backdrop-blur">
          <p className="text-sm opacity-80">🎒 Style</p>
          <p className="mt-2 text-2xl font-bold">
            {overview.style}
          </p>
        </div>

        <div className="rounded-2xl bg-white/15 p-5 backdrop-blur">
          <p className="text-sm opacity-80">🤖 Generated By</p>
          <p className="mt-2 text-2xl font-bold">
            Gemini AI
          </p>
        </div>

      </div>
    </div>
  );
};

export default TripOverview;